version: '3.8'
services:
  # The Message Broker (Data Highway)
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    ports:
      - "9092:9092"
    command: ["redpanda", "start", "--overprovisioned", "--smp", "1", "--memory", "1G", "--reserve-memory", "0M", "--node-id", "0", "--check=false"]

  # The Database (Storage)
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"

  # The Dashboard (Visualization)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"